In [112]:
import pandas as pd

In [113]:
df = pd.read_csv("dataset/laptop_mini_dataset.csv")

In [114]:
df.head(10)

,product_id,Brand,Ram,Storage,Display,Touch,Color,Build_quality,OS,Price
0,1,Lenovo,32GB,256GB SSD,15.6 inch,Yes,Silver,Good,Linux,2093.25
1,2,Acer,32GB,256GB SSD,15.6 inch,Yes,Gray,Good,Windows,1502.22
2,3,HP,32GB,1TB SSD,16 inch,Yes,Silver,Good,Linux,1352.69
3,4,Lenovo,32GB,256GB SSD,15.6 inch,Yes,Gray,Excellent,Windows,2416.28
4,5,Asus,4GB,256GB SSD,16 inch,Yes,Gray,Good,Windows,2381.78
5,6,Acer,32GB,256GB SSD,15.6 inch,Yes,Black,Excellent,Linux,2140.34
6,7,Dell,16GB,256GB SSD,14 inch,Yes,Gray,Good,Linux,798.69
7,8,Asus,32GB,512GB SSD,14 inch,No,Silver,Fair,Linux,574.97
8,9,HP,4GB,512GB SSD,16 inch,Yes,Black,Excellent,Windows,1912.10
9,10,Acer,4GB,1TB SSD,15.6 inch,Yes,Silver,Fair,Windows,610.71

In [115]:
df.tail(10)

,product_id,Brand,Ram,Storage,Display,Touch,Color,Build_quality,OS,Price
20,21,HP,8GB,512GB SSD,15.6 inch,Yes,Gray,Fair,Windows,895.68
21,22,Apple,8GB,512GB SSD,16 inch,No,NaN,Fair,MacOS,1515.62
22,23,Apple,8GB,512GB SSD,13.3 inch,Yes,Gray,Good,Windows,1531.43
23,24,Apple,8GB,512GB SSD,13.3 inch,No,Gray,Good,Windows,824.28
24,25,HP,8GB,1TB SSD,14 inch,No,NaN,Fair,Windows,1324.18
25,26,Apple,4GB,1TB SSD,15.6 inch,No,Silver,Excellent,MacOS,1963.29
26,27,Lenovo,4GB,512GB SSD,13.3 inch,Yes,Gray,Fair,Linux,442.81
27,28,Asus,8GB,1TB SSD,14 inch,Yes,Silver,Fair,MacOS,477.80
28,29,Dell,16GB,1TB SSD,16 inch,No,Silver,Good,Linux,2060.61
29,30,Lenovo,8GB,512GB SSD,16 inch,Yes,Gray,Fair,MacOS,2328.25

In [116]:
df.columns

Index(['product_id', 'Brand', 'Ram', 'Storage', 'Display', 'Touch', 'Color',
       'Build_quality', 'OS', 'Price'],
      dtype='object')

In [117]:
df.shape

(30, 10)

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     30 non-null     int64
 1   Brand          30 non-null     object
 2   Ram            30 non-null     object
 3   Storage        30 non-null     object
 4   Display        30 non-null     object
 5   Touch          30 non-null     object
 6   Color          27 non-null     object
 7   Build_quality  30 non-null     object
 8   OS             30 non-null     object
 9   Price          30 non-null     float64
dtypes: float64(1), int64(1), object(8)
memory usage: 2.5+ KB

In [119]:
df.isnull().sum()

product_id       0
Brand            0
Ram              0
Storage          0
Display          0
Touch            0
Color            3
Build_quality    0
OS               0
Price            0
dtype: int64

In [120]:
df.describe()

       product_id        Price
count   30.000000    30.000000
mean    15.500000  1542.717333
std      8.803408   684.241243
min      1.000000   417.930000
25%      8.250000   842.130000
50%     15.500000  1719.250000
75%     22.750000  2085.775000
max     30.000000  2480.850000

In [121]:
df.isnull().sum()

product_id       0
Brand            0
Ram              0
Storage          0
Display          0
Touch            0
Color            3
Build_quality    0
OS               0
Price            0
dtype: int64

In [122]:
c_mode = df["Color"].mode()[0]

c_mode

'Gray'

In [123]:
df["Color"].fillna(c_mode, inplace=True)

C:\Users\aabidkhokhar\AppData\Local\Temp\ipykernel_13044\572663527.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Color"].fillna(c_mode, inplace=True)

In [125]:
df.isnull().sum()

product_id       0
Brand            0
Ram              0
Storage          0
Display          0
Touch            0
Color            0
Build_quality    0
OS               0
Price            0
dtype: int64